laserscan_multi_merger_node:
  ros__parameters:
    destination_frame: "lidar_merge_link"
    scan_destination_topic: "lidar_merge/scan"
    laserscan_topics: "lidar_left/scan lidar_right/scan"
    angle_min: -3.14
    angle_max: 3.14
    angle_increment: 0.00174
    scan_time: 0.05
    range_min: 0.1
    range_max: 20.0
    use_inf: False
    allow_scan_delay: True
    max_delay_scan_time: 0.05 # if scan delay is allowed
    max_completion_time: 0.05
    max_merge_time_diff: 0.05
    best_effort: True
