laserscan_multi_merger_node:
  ros__parameters:
    destination_frame: "odom"
    scan_destination_topic: "merged_scan"
    laserscan_topics: "lidar_front/scan lidar_left/scan lidar_right/scan"
    angle_min: -1.57079632679
    angle_max: 1.57079632679
    angle_increment: 0.01163552834
    scan_time: 0.06666666666
    range_min: 0.1
    range_max: 10.0
    use_inf: False
    allow_scan_delay: True
    max_delay_scan_time: 0.02 # if scan delay is allowed
    max_completion_time: 0.02
    max_merge_time_diff: 0.02
    best_effort: True
